#	D I G I T I Z E R
/gate/digitizer/Singles/insert adder
/gate/digitizer/Singles/insert readout
/gate/digitizer/Singles/readout/setDepth 3
/gate/digitizer/Singles/insert blurring
/gate/digitizer/Singles/blurring/setResolution 0.12
/gate/digitizer/Singles/blurring/setEnergyOfReference 511. keV
/gate/digitizer/Singles/insert blurring2
/gate/digitizer/Singles/insert thresholder
/gate/digitizer/Singles/thresholder/setThreshold 50. keV
/gate/digitizer/Singles/insert upholder
/gate/digitizer/Singles/upholder/setUphold 1150. keV



#	C O I N C I    S O R T E R
/gate/digitizer/Coincidences/setInputName Singles
/gate/digitizer/Coincidences/setWindow 6. ns
/gate/digitizer/Coincidences/MultiplesPolicy takeAllGoods

#/gate/digitizer/name delay
#/gate/digitizer/insert coincidenceSorter
#/gate/digitizer/delay/setWindow 120. ns
#/gate/digitizer/delay/setOffset 500. ns
#/gate/digitizer/delay/MultiplesPolicy  takeWinnerOfGoods
