/gate/source/addSource LUsource_A
/gate/source/LUsource_A/gps/particle ion
/gate/source/LUsource_A/gps/ion 71 176
/gate/source/LUsource_A/setForcedUnstableFlag true
/gate/source/LUsource_A/setForcedHalfLife 360806000000 s
/gate/source/LUsource_A/gps/angtype iso
/gate/source/LUsource_A/gps/energytype Mono
/gate/source/LUsource_A/gps/monoenergy 0. MeV
/gate/source/LUsource_A/setActivity 17000 becquerel
/gate/source/LUsource_A/attachTo rsector
/gate/source/LUsource_A/gps/type Volume
/gate/source/LUsource_A/gps/shape Para
/gate/source/LUsource_A/gps/halfx 7.5 mm
/gate/source/LUsource_A/gps/halfy 32. mm
/gate/source/LUsource_A/gps/halfz 32. mm
#/gate/source/LUsource_A/gps/centre 0 0 0 mm

/gate/source/addSource LUsource_B
/gate/source/LUsource_B/gps/particle ion
/gate/source/LUsource_B/gps/ion 71 176
/gate/source/LUsource_B/setForcedUnstableFlag true
/gate/source/LUsource_B/setForcedHalfLife 360806000000 s
/gate/source/LUsource_B/gps/angtype iso
/gate/source/LUsource_B/gps/energytype Mono
/gate/source/LUsource_B/gps/monoenergy 0. MeV
/gate/source/LUsource_B/setActivity 17000 becquerel
/gate/source/LUsource_B/attachTo rsector
/gate/source/LUsource_B/gps/type Volume
/gate/source/LUsource_B/gps/shape Para
/gate/source/LUsource_B/gps/halfx 7.5 mm
/gate/source/LUsource_B/gps/halfy 32. mm
/gate/source/LUsource_B/gps/halfz 32. mm
#translation: 2*Rmin + 2*rsectorX/2
/gate/source/LUsource_B/gps/centre -129.6 0 0 mm
