/gate/source/addSource Na22_Z0_X0
/gate/source/Na22_Z0_X0/setType backtoback
/gate/source/Na22_Z0_X0/gps/centre 0. 0. 0. mm
/gate/source/Na22_Z0_X0/gps/particle gamma
/gate/source/Na22_Z0_X0/gps/energytype Mono
/gate/source/Na22_Z0_X0/gps/monoenergy 0.511 MeV
/gate/source/Na22_Z0_X0/gps/type Volume
/gate/source/Na22_Z0_X0/gps/shape Sphere
/gate/source/Na22_Z0_X0/gps/radius 1 mm
/gate/source/Na22_Z0_X0/gps/angtype iso


/gate/source/Na22_Z0_X0/gps/mintheta 60. deg
/gate/source/Na22_Z0_X0/gps/maxtheta 120. deg
/gate/source/Na22_Z0_X0/gps/minphi 0. deg
/gate/source/Na22_Z0_X0/gps/maxphi 360. deg

#/gate/source/Na22_Z0_X0/visualize 1000 red 2
